# # Definitions of tags to detect
#
# ## General remarks
#
# - All length in meters
# - Ellipsis (...) signifies that the previous element can be repeated multiple times.
#
# ## Standalone tag definitions
# ### Remarks
#
# - name is optional
#
# ### Syntax
#
# standalone_tags:
#   [
#     {id: ID, size: SIZE, name: NAME},
#     ...
#   ]
standalone_tags:
  [
  ]
# ## Tag bundle definitions
# ### Remarks
#
# - name is optional
# - x, y, z have default values of 0 thus they are optional
# - qw has default value of 1 and qx, qy, qz have default values of 0 thus they are optional
#
# ### Syntax
#
# tag_bundles:
#   [
#     {
#       name: 'CUSTOM_BUNDLE_NAME',
#       layout:
#         [
#           {id: ID, size: SIZE, x: X_POS, y: Y_POS, z: Z_POS, qw: QUAT_W_VAL, qx: QUAT_X_VAL, qy: QUAT_Y_VAL, qz: QUAT_Z_VAL},
#           ...
#         ]
#     },
#     ...
#   ]
tag_bundles:
  [
    {
      name: 'my_bundle',
      layout:
        [
          #{id: 0, size: 0.162, x: 2, y: 0, z: 0, qw: 0.707, qx: 0.0, qy: 0.0, qz: -0.707},
          #{id: 0, size: 0.162},
          #{id: 1, size: 0.162},
          #{id: 2, size: 0.162},
          #{id: 3, size: 0.162},
          #{id: 4, size: 0.162},
          #{id: 5, size: 0.162},
          #{id: 6, size: 0.162},
          #{id: 7, size: 0.162, x: 2, y: 0, z: 0, qw: 0.707, qx: 0.0, qy: 0.0, qz: -0.707},
          #{id: 8, size: 0.162},
          #{id: 9, size: 0.162},
          #{id: 10, size: 0.162},
          #{id: 11, size: 0.162},
          #{id: 12, size: 0.162},
          {id: 23, size: 0.162, x: 0, y: 0, z: 0, qw: 0.707, qx: 0.0, qy: 0.0, qz: -0.707},
          {id: 12, size: 0.162, x: 0, y: -0.5, z: 0, qw: 0.707, qx: 0.0, qy: 0.0, qz: -0.707},
          {id: 13, size: 0.162, x: 2.5, y: 0, z: 0, qw: 0.707, qx: 0.0, qy: 0.0, qz: -0.707},
          {id: 0, size: 0.162, x: 2.5, y: -1, z: 0, qw: 0.707, qx: 0.0, qy: 0.0, qz: -0.707},
          {id: 20, size: 0.162, x: 2.77, y: -2, z: 0, qw: -0.5, qx: 0.5, qy: -0.5, qz: 0.5},
          {id: 10, size: 0.162, x: 1.5, y: -2.5, z: 0, qw: 0.707, qx: 0.0, qy: 0.0, qz: -0.707},
          {id: 2, size: 0.162, x: 2.5, y: -3, z: 0, qw: 0.707, qx: 0.0, qy: 0.0, qz: -0.707},
          {id: 19, size: 0.162, x: 2.77, y: -4, z: 0, qw: -0.5, qx: 0.5, qy: -0.5, qz: 0.5},
          {id: 6, size: 0.162, x: 1.5, y: -5, z: 0, qw: 0.707, qx: 0.0, qy: 0.0, qz: -0.707},
          {id: 4, size: 0.162, x: 2.5, y: -5, z: 0, qw: 0.707, qx: 0.0, qy: 0.0, qz: -0.707},
          {id: 5, size: 0.162, x: 2.5, y: -6, z: 0, qw: 0.707, qx: 0.0, qy: 0.0, qz: -0.707},
          {id: 18, size: 0.162, x: 2.77, y: -6.5, z: 0, qw: -0.5, qx: 0.5, qy: -0.5, qz: 0.5},
          {id: 17, size: 0.162, x: 2.77, y: -8.5, z: 0, qw: -0.5, qx: 0.5, qy: -0.5, qz: 0.5},
          {id: 7, size: 0.162, x: 0, y: -3.5, z: 0, qw: 0.707, qx: 0.0, qy: 0.0, qz: -0.707},
          {id: 11, size: 0.162, x: 0, y: -6.5, z: 0, qw: 0.707, qx: 0.0, qy: 0.0, qz: -0.707},
          {id: 16, size: 0.162, x: 0, y: -8, z: 0, qw: 0.707, qx: 0.0, qy: 0.0, qz: -0.707},
          {id: 22, size: 0.162, x: -1.5, y: 0, z: 0, qw: 0.707, qx: 0.0, qy: 0.0, qz: -0.707},
          {id: 9, size: 0.162, x: -1.5, y: -2.5, z: 0, qw: 0.707, qx: 0.0, qy: 0.0, qz: -0.707},
          {id: 8, size: 0.162, x: -1.5, y: -5, z: 0, qw: 0.707, qx: 0.0, qy: 0.0, qz: -0.707},
          {id: 15, size: 0.162, x: -1.5, y: -8, z: 0, qw: 0.707, qx: 0.0, qy: 0.0, qz: -0.707},
          {id: 21, size: 0.162, x: -2, y: -2, z: 0, qw: 0.707, qx: 0.0, qy: 0.0, qz: -0.707},
          {id: 14, size: 0.162, x: -2, y: -6, z: 0, qw: 0.707, qx: 0.0, qy: 0.0, qz: -0.707},
          {id: 1, size: 0.162, x: -0.5, y: 1, z: 0, qw: 0.707, qx: 0.0, qy: 0.0, qz: -0.707},

          #{id: 5, size: 0.162, x: 3.25, y: 5.5, z: 0, qw: -0.5, qx: 0.5, qy: -0.5, qz: 0.5},
        ]
    }
  ]
